Overengineering style check

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -13,11 +13,25 @@ jobs:
           sudo apt install -y clang-format
       - name: "Run stylecheck"
         run: |
-          clang-format -Werror --dry-run \
-              src/*.cpp src/*.hpp \
-              tests/*.cpp tests.*.hpp
-          #clang-format -i src/*.cpp src/*.hpp tests/*.cpp tests.*.hpp > /dev/null 2>&1 || echo "Consider the following changes: " && git --no-pager diff && exit -1
-
+          # Overengineering the style check for fun...
+          stylecheck="clang-format -Werror --dry-run src/*.cpp src/*.hpp tests/*.cpp"
+          
+          if $stylecheck ; then \
+              echo "$(tput setaf 2)No style errors found :)$(tput setaf 7)"; \
+          else \
+              echo "$(tput setaf 1)Clang-format found errors :($(tput setaf 7)"; \
+              clang-format -i src/*.cpp src/*.hpp tests/*.cpp; \
+              echo "Consider the following changes:"; \
+              git --no-pager diff; \
+              echo "You can use $(tput setaf 3)clang-format -i$(tput setaf 7) to apply these changes to your code."; \
+              exit 1; \
+          fi
+          
+          # This also works just fine
+          #clang-format -Werror --dry-run \
+          #    src/*.cpp src/*.hpp \
+          #    tests/*.cpp
+              
   build:
     runs-on: ubuntu-latest
     strategy:
